name: infx-api API Unit Tests

on:
  pull_request:

jobs:
  python-test:
    uses: projectronin/github/.github/workflows/python_test.yml@master
    secrets:
      codecov-token: ${{ secrets.INFX_API_CODECOV_TOKEN  }}
