name: Hashi API Deployment to K8s

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  python-test:
    uses: projectronin/github/.github/workflows/python_test.yml@master
    secrets:
      codecov-token: ${{ secrets.HASHI_CODECOV_TOKEN }}

  get-tags:
    name: Standard tags
    runs-on: ubuntu-18.04
    outputs:
      helm_tag: ${{ steps.git_info.outputs.helm_tag }}

    steps:
    - name: Check out code
      uses: actions/checkout@v2.1.0

    - name: github information
      id: git_info
      run: |
        TAG=$(cat deployment/helm/hashi/Chart.yaml | grep version | egrep -o '[0-9]+\.[0-9]+\.[0-9]+')
        echo ${TAG}
        echo ::set-output name=helm_tag::$(echo ${TAG})

  image-push:
    uses: projectronin/github/.github/workflows/image_push.yml@master
    with:
      image-tag: ${{ github.sha }}
      repo: 'hashi'
    secrets:
      username: ${{ secrets.ACR_USERNAME }}
      password: ${{ secrets.ACR_PASSWORD }}      

  helm:
    uses: projectronin/github/.github/workflows/helm_push.yml@master
    with:
      repo: 'hashi'
    secrets:
      helm-repo: ${{ secrets.HELM_REPO }}
      helm-password: ${{ secrets.HELM_PASSWORD }}

  k8s:
    uses: projectronin/github/.github/workflows/k8s_deploy.yml@master
    needs: [python-test,get-tags,image-push,helm]
    with:
      environment: prod
      cluster-name: aks-prod-centralus
      resource-group: rg-infra-k8s-prod
      helm-tag: ${{ needs.get-tags.outputs.helm_tag }}
      image-tag: ${{ github.sha }}
      repo: 'hashi'
    secrets:
      helm-repo: ${{ secrets.HELM_REPO }}
      helm-password: ${{ secrets.HELM_PASSWORD }}
      azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
